### ISSUE TITLE
Giga-piano training time

### ISSUE THREAD

**Issue by TommasoBorghesi612** [asigalov61/GIGA-Piano#1]
Hi,
First of all thanks for all the amazing repos about music generation that you have been making, they're amazing.

My problem is about data and mostly training times.
In the readme you submitted in GIGA-Piano/Model you say that the net was
'Trained upon 1.7GB of solo piano music for 4 epochs (120k steps/~64 hours) @ 28 batches on dual A6000 GPUs'.

But there are two things that are not clear to me:

The first is that if i download the three midi datasets (ALL-Piano Dataset, GiantMIDI Dataset and MAESTRO Dataset) their combined uncompressed size is about 586 MB instead of 1.7GB so i'm wondering if i'm missing some data.

The second (and the most important) is about training times, i am currently using 1 Nvidia RTX A6000 (64GB RAM) (so i have exactly half of your computing power) but the training times are way higher than expected, and it seems that to perform an epoch (on the 586 MB dataset) it takes more than one year which is kinda too much for any reasonable training. The main problem i have with this time is that is pretty much consistent with the approx time showed on colab when i run the GIGA_Piano_Maker.ipynb notebook.
Since i use only one GPU i tried to comment the nn.Dataparallel(model) line but with no changes in performance.

I would like to know if i could get some advice about the problems i have since i would really like to train those net to make some music.

Also, when you say '28 batches' you mean that the batch_size was = 28?

In any case thank you for your time and thank you more for your work.
Have a nice day.

**Comment by TommasoBorghesi612** [comment]
Every parameter i did not specified was the same as in the repo files (for example my batch size is 4 GPT config are dim_feedforward=1024, n_layer=16, n_head=16, n_embd=1024 etc...)

**Comment by asigalov61** [comment]
@TommasoBorghesi612 Thank you for your questions and thank you for your kind words.

GIGA Piano was trained on a custom MIDI piano scrape. So you are indeed missing some data. I will add a note to the repo so that it is clear.

I used MMD piano extract + LAKH piano extract + GiantMIDI + MAESTRO + ALL-Piano. This is pretty much a full list of datasets used.

In regard to training time, please do not pay attention to the calculated training time because it is not correct. This is because I need to correct the dataloader code. Instead, calculate the needed time manually. For example, if you go by the original training data (1.7 GB), which is 902840320 ints, your epoch @ 28 batches on 2 A6000 GPUs would be 902840320 // 1024 // 28 == 31488 steps, which would take you to train approx 15-20 hours per epoch.

Otherwise, please use the provided colab because it is exactly the code that was used to train GIGA-Piano and if you want to reproduce the results presented in the repo.

Again, please note that I used TWO (2) A6000 GPUs 48 GB @ 28 batches with a DataParallel wrapper.

Hope this answers your questions. Please let me know if you need more clarifications.

Thank you

Alex

**Comment by asigalov61** [comment]
@TommasoBorghesi612 I may add the original processed training data file to the repo. If you like, contact me directly @ asigalov61@hotmail.com if you want the original processed training data file for private use.

Thanks.

**Comment by asigalov61** [comment]
@TommasoBorghesi612 I've added original training data to the repo. Let me know if you have any questions or problems with using it.

Thanks.

https://github.com/asigalov61/GIGA-Piano/tree/main/Training-Data

**Comment by TommasoBorghesi612** [comment]
Thank you very much, your response was very appreciated along with the data you uploaded to the repo.
I will do some tests now, with the new datasets, in which i will calculate the training times like you said.

If there are further things i may need to ask mabye i can send you an email in the future with some questions about the training process and stuff (since you were so kind to tell me your email adress, if it's not too much to ask of course).

But for now i think i can close this issue.
Thanks again.
